### ISSUE TITLE
Generating Test Loss

### ISSUE THREAD

**Issue by VassMorozov** [MCG-NJU/BCN#10]
Hi,

Have you got code to produce the test loss per epoch for the BCN component? 

If not is this better done at training or at prediction point?

Thanks for your contribution!

**Comment by zhenzhiwang** [comment]
Hi [VassMorozov](https://github.com/VassMorozov),

You can implement it by yourself based on our code to explore its effectiveness.

**Comment by VassMorozov** [comment]
I have looked into this and a little bit unsure on a couple of bits.

Regarding the adjustable weights coming out of the stage cascade (`adjust_weight`):

`predictions,BGM_output,adjust_weight = self.cascadeModel(batch_input, mask, gt_target=batch_target,soft_threshold=0.8)`

Should this be the same weight as used during the training or must one be calculated for the test as well?

**Comment by VassMorozov** [comment]
Sorry I think I have been incredibly stupid but have worked it out...
