### ISSUE TITLE
pre-training BGM

### ISSUE THREAD

**Issue by Forgetmmmm** [MCG-NJU/BCN#11]
Hello，I would like to ask how do I determine how many epochs I want to train when pre-training the BGM module.Since it is co-trained with SC again in the later, I don't know how many rounds of pre-training and co-training can achieve better results.Maybe my question is a little too simple, but I still hope to receive your reply, thank you!

**Comment by zhenzhiwang** [comment]
I think number of epochs in training BGM has little impact on the final result. You can try a few hundreds epochs (e.g., 200-400 according to my memory) and the training procedure is very fast (e.g., 10-20 minutes with single GPU). You can stop as long as the precision and recall are stable. Or the simplest way is to see whether the difference of f1 score of adjacent epochs is less than a small threshold. Please be free to ask questions. I will reply once I saw it.

**Comment by Forgetmmmm** [comment]
Thank you for your reply！The pre-trained BGM module provides relatively accurate boundaries for subsequent training. Is it impossible to generate accurate boundaries without using pre-training? But it seems to be possible to achieve better results without using pre-trained models. Can you explain that?

**Comment by zhenzhiwang** [comment]
I think pretrain or not is an implementation detail which is not important for my paper. By training BGM and SC for enough epochs, I believe BGM is also able to predict accurate boundaries. Yet, it is not necessary for SC to train such amount of epochs. You could try such experiments by yourself if you are interested in it.

**Comment by Forgetmmmm** [comment]
Thank you for your answer! I don't quite understand the idea of LBP in the paper. There are several questions as follows: How to combine boundary information and original prediction in LBP? Why should I reduce the weight when facing barrier? What does this weight do on this side? Hope to get your help, thank you again!

**Comment by zhenzhiwang** [comment]
I think the details of LBP in the paper is clear enough. The idea of LBP is to make  smoother action predictions within action instances with the help of predicted action boundaries.
