### ISSUE TITLE
Visual result

### ISSUE THREAD

**Issue by BALDman66** [MCG-NJU/BCN#8]
Hello, first of all thank you very much for the code and then I would like to ask how can I get this visualization result
![image](https://user-images.githubusercontent.com/59443639/147627715-3f3f102c-2be2-4f56-9aeb-92d4f6a76e30.png)

**Comment by zhenzhiwang** [comment]
Thank you for your interest of our paper. The visualization is based on the raw output of our model or the baseline. However, we have no plan to release the visualization code. You could try to implement it by yourself if you need to visualize your own model.
